services:
  proxy:
    build:
        context: .
        dockerfile: ./proxy/Dockerfile
    environment:
      FUNCTIONS: "animus"
    volumes:
      - ./proxy:/app
    restart: always
    ports:
      - "8080:8080"
  animus:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      FUNCTION_TARGET: Animus
    volumes:
      - ./animus:/app
    restart: always
