version: '3'

tasks:
  generate-opus:
    desc: "go generate for opus"
    dir: "opus"
    cmds:
      - go install go.uber.org/mock/mockgen@latest
      - go install golang.org/x/tools/cmd/stringer@latest
      - export PATH=$PATH:$(go env GOPATH)/bin
      - go generate ./...
  test-opus:
    desc: "Run the test for opus"
    dir: "opus"
    cmds:
      - go test ./...
  coverage-opus:
    desc: "Run the coverage for opus"
    dir: "opus"
    cmds:
      - go test -coverprofile=./coverage.txt ./...
      - go tool cover -html=./coverage.txt
