# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "develop" ]
    paths:
        - 'opus/**'
        - '.github/workflows/opus-pr.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: opus
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: go.sum

    - name: Test
      run: go test -v ./... -coverprofile=coverage.out --covermode=atomic

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: opus
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: go.sum

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0
      with:
        args: --config=../.golangci.yml
